# Generated by Django 4.0.3 on 2022-05-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_usercategory_category_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to='news.category'),
        ),
    ]
