# Generated by Django 4.0.3 on 2022-05-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_author_en_us_post_author_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creation_date_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creation_date_ru',
        ),
    ]
