# Generated by Django 4.0.3 on 2022-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_post_author_en_us_remove_post_author_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(help_text='post title', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title_en_us',
            field=models.CharField(help_text='post title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title_ru',
            field=models.CharField(help_text='post title', max_length=255, null=True),
        ),
    ]
